/* eslint-disable */
export const brands = [
    {
        id   : '9a67dff7-3c38-4052-a335-0cef93438ff6',
        name: 'BMW',
        badge : 'bmw'
    },
    {
        id   : 'a89672f5-e00d-4be4-9194-cb9d29f82165',
        name: 'Toyota',
        badge : 'toyota'
    },
    {
        id   : '02f42092-bb23-4552-9ddb-cfdcc235d48f',
        name: 'Hyundai',
        badge : 'hyundai'
    },
    {
        id   : '5648a630-979f-4403-8c41-fc9790dea8cd',
        name: 'Kia',
        badge : 'kia'
    }
];
export const cars = [
    {
        id         : '694e4e5f-f25f-470b-bd0e-26b1d4f64028',
        brand      : 'toyota',
        model      : 'Camry',
        description: '6 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/bmw-i.png',
        year       : 2022,
        fuelType   : 'Gasolina',
        price      : 25000,
        mileage    : 15000,
        condition  : 'Usado',
        available  : true,
    },
    {
        id         : 'f924007a-2ee9-470b-a316-8d21ed78277f',
        brand      : 'kia',
        model      : 'Civic',
        description: '4 asientos, 2 puertas, 4 cilindros',
        image      : 'assets/images/cars/kia-civic.png',
        year       : 2023,
        fuelType   : 'Gasolina',
        price      : 22000,
        mileage    : 0,
        condition  : 'Nuevo',
        available   : false,
    },
    {
        id         : '0c06e980-abb5-4ba7-ab65-99a228cab36b',
        brand      : 'hyundai',
        model      : 'Elantra',
        description: '5 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/hyundai-elantra.png',
        year       : 2022,
        fuelType   : 'Eléctrico',
        price      : 23000,
        mileage    : 12000,
        condition  : 'Usado',
        available  : true,
    },
    {
        id         : '1b9a9acc-9a36-403e-a1e7-b11780179e38',
        brand      : 'bmw',
        model      : 'X3',
        description: '5 asientos, 4 puertas, 6 cilindros',
        image      : 'assets/images/cars/bmw-x3.png',
        year       : 2021,
        fuelType   : 'Gasolina',
        price      : 40000,
        mileage    : 8000,
        condition  : 'Usado',
        available  : true,
    },
    {
        id         : '55eb415f-3f4e-4853-a22b-f0ae91331169',
        brand      : 'toyota',
        model      : 'Rav4',
        description: '5 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/toyota-rav4.png',
        year       : 2020,
        fuelType   : 'Híbrido',
        price      : 32000,
        mileage    : 10000,
        condition  : 'Usado',
        available  : false,
    },
    {
        id         : 'fad2ab23-1011-4028-9a54-e52179ac4a50',
        brand      : 'kia',
        model      : 'Sportage',
        description: '5 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/kia-sportage.png',
        year       : 2023,
        fuelType   : 'Gasolina',
        price      : 27000,
        mileage    : 0,
        condition  : 'Nuevo',
        available   : true,
    },
    {
        id         : '7e4a9bb3-292f-4f4f-8e08-12584bb20810',
        brand      : 'hyundai',
        model      : 'Tucson',
        description: '5 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/hyundai-tucson.png',
        year       : 2021,
        fuelType   : 'Gasolina',
        price      : 28000,
        mileage    : 9000,
        condition  : 'Usado',
        available  : true,
    },
    {
        id         : 'c5a2ec4a-464c-49ac-b5de-e8c6a703e7c7',
        brand      : 'toyota',
        model      : 'Corolla',
        description: '5 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/toyota-corolla.png',
        year       : 2023,
        fuelType   : 'Híbrido',
        price      : 26000,
        mileage    : 2000,
        condition  : 'Nuevo',
        available  : true,
    },
    {
        id         : 'd8e7221e-bd8b-4094-b56c-4b9c84cfa648',
        brand      : 'bmw',
        model      : 'M3',
        description: '4 asientos, 4 puertas, 4 cilindros',
        image      : 'assets/images/cars/bmw-m3.png',
        year       : 2022,
        fuelType   : 'Gasolina',
        price      : 38000,
        mileage    : 7000,
        condition  : 'Usado',
        available  : false,
    },
    {
        id         : '2e5e8b0b-fac1-4d0b-8a7e-431982c2f95d',
        brand      : 'toyota',
        model      : 'GR Supra',
        description: '2 asientos, 2 puertas, 8 cilindros',
        image      : 'assets/images/cars/toyota-supra.png',
        year       : 2023,
        fuelType   : 'Gasolina',
        price      : 450000,
        mileage    : 0,
        condition  : 'Nuevo',
        available  : true,
    }
];

